contentColumnType: text
fieldGroup: 21515fbb-8d8a-4b8b-956d-58972a8fbd45
handle: longitude
instructions: ''
name: Longitude
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
