contentColumnType: integer(10)
fieldGroup: ad9b672f-ea7c-4b45-ad43-ac2cccfda932
handle: order
instructions: ''
name: order
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '1'
  prefix: ''
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
