dateModified: 1611860926
email:
  fromEmail: yahmed1996a@gmail.com
  fromName: 'http://localhost/goodbeer_project'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'Contact Form via GoodBeer:'
      prependSubject: 'New Contact message Good Beer'
      successFlashMessage: 'Your message has been sent.'
      toEmail: webmaster@whitespacers.com
  guest-entries:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
    settings:
      enableCsrfProtection: '1'
      entryVariable: entry
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: GoodBeer
  retryDuration: null
  schemaVersion: 3.6.1
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
