enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  15e18493-66bb-4b32-8b3b-5a7729652f09:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
