enableVersioning: true
handle: ourProducts
name: 'Our Products'
propagationMethod: all
siteSettings:
  15e18493-66bb-4b32-8b3b-5a7729652f09:
    enabledByDefault: true
    hasUrls: true
    template: our-products
    uriFormat: 'our-products/{slug}'
structure:
  maxLevels: null
  uid: e8b154d2-d843-45d5-8857-c2dc9df0b7bb
type: structure
