enableVersioning: true
handle: stockists
name: Stockists
propagationMethod: all
siteSettings:
  15e18493-66bb-4b32-8b3b-5a7729652f09:
    enabledByDefault: true
    hasUrls: true
    template: stockists/singleStockist
    uriFormat: 'stockists/{slug}'
type: channel
