enableVersioning: true
handle: termsAndConditions
name: 'Terms and Conditions'
propagationMethod: all
siteSettings:
  15e18493-66bb-4b32-8b3b-5a7729652f09:
    enabledByDefault: true
    hasUrls: true
    template: terms-and-conditions
    uriFormat: terms-and-conditions
type: single
