enableVersioning: true
handle: thanks
name: Thanks
propagationMethod: all
siteSettings:
  15e18493-66bb-4b32-8b3b-5a7729652f09:
    enabledByDefault: true
    hasUrls: true
    template: thanks
    uriFormat: thank-you
type: single
